"""Create register model

Revision ID: 7ba439f7494d
Revises: 
Create Date: 2022-06-21 09:53:41.408456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba439f7494d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_data', sa.String(length=1000), nullable=False),
    sa.Column('dev1', sa.String(length=20), nullable=False),
    sa.Column('dev2', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register_data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register_model')
    # ### end Alembic commands ###
